### ISSUE TITLE
What can I work on ? (tracker issue)

### ISSUE THREAD

**Issue by teolemon** [juliansteenbakker/mobile_scanner#260]
#### Camera switching
- #118
- #214
#### Device orientation
- #107
- #239 
#### Limiting scan area
- #11 and #119
### Android specific issues
- [ ] #259 
- [x] #197
- [x] #189
### Windows specific issues
- #14
- #204
### iOS specific issues
- #132 
- #131 
- #190
- #164 
- #144
- #212
### macOS specific issues
- [x] #241 
- [x] #236 
- [ ] #230 
- [x] #205
### Web specific issues
- #54
- #57
- #118
- #222
### Performance
- #136
### DevOps (Android)
- [x] #223
### Other
- [ ] Add screenshots of the scanner in the README
- [ ] Add a list of known issues in the README
- [ ] Release a new version of the package

**Comment by maulikchak** [comment]
#57

Camera not working after deploying - Flutter web on mobile browser (on Safari)

https://github.com/juliansteenbakker/mobile_scanner/issues/57

**Comment by nilsreichardt** [comment]
Maybe you pick my closed PR on adding an integration test for Android: https://github.com/juliansteenbakker/mobile_scanner/pull/121. Having an integration test would be super sick and ensure that this package is really working.

**Comment by maulikchak** [comment]
Camera not working after deploying - Flutter web on mobile browser (on Safari) @nilsreichardt @teolemon @juliansteenbakker 
 please look in to this

#57
